### ISSUE TITLE
missing files de.ecconia.java.json.JSONObject;

### ISSUE THREAD

**Issue by BarryV94** [Ecconia/Minecraft-Launcher-Java#1]
hey i was trying to use your launcher but it appears that you forgot to add files like :

import de.ecconia.java.json.JSONObject;
import de.ecconia.java.json.JSONParser;

The files are missing :)

**Comment by Ecconia** [comment]
Haven't looked into this project in like 3 or 4 months.
Just opened it and didn't find any issues.

I assume you didn't use maven to compile the project - correct me if I am wrong.

The JSON library is delivered as maven dependency, my server is up. If you compile the project with maven it should download the JSON classes: `mvn package`

Some IDE's (eclipse) do that by themself (if imported as maven project), while IntelliJ had some issues for me. But `mvn package` should always work.

If it still doesn't work, or you are already using maven, please send me more details :)

**Comment by Ecconia** [comment]
If you got that running, don't forget to put your UUID here https://github.com/Ecconia/Minecraft-Launcher-Java/blob/418331675229f427e4b74ebd017fa24872a0f620/src/main/java/de/ecconia/mclauncher/data/RunArguments.java#L134 and your AccessToken here https://github.com/Ecconia/Minecraft-Launcher-Java/blob/418331675229f427e4b74ebd017fa24872a0f620/src/main/java/de/ecconia/mclauncher/data/RunArguments.java#L138

You can get the access token from the Mojang API, or just copy it from the `launcher_profiles.json` file in your normal (java) launcher. I was too lazy to put query code into the launcher yet. I could do that though.

I wonder why I stopped using this launcher, I just downloaded and ran 1.15.2 and it worked fine. I should add code to refresh the access token for sure.

*EDIT: Class is the same, but lines changed. User insertion might change in future!

**Comment by BarryV94** [comment]
OMG totally forgot about maven ..... It works well

is there any way to contact with you via email or discord ?
